joindin/joindin-web2

app/src/User/UserController.php
app/src/User/UserDb.php

This was missing from the user profile work.

Save the user's data under the username key

---

app/templates/_common/pagination.html.twig

Make pagination work when listing events by tag

---

app/src/Event/EventApi.php
app/src/Search/SearchController.php
app/src/Talk/TalkApi.php
app/templates/Application/search.html.twig
app/templates/Talk/_common/summary.html.twig
app/templates/layout.html.twig
web/css/joindin.css
web/js/joindin.js

Depends on the talk search PR for the API: https://github.com/joindin/joindin-api/pull/135
The search form in header searches now also talks. Results are shown side-by-side on big screens and talks below events on mobile.
https://joindin.jira.com/browse/JOINDIN-277

JOINDIN-277 Talk search

---

README.md

This commit removes the instructions for a local setup in favour of
using the VM-setup

Removes the local setup in favour of vagrant setup

---

app/src/Event/EventDb.php
app/src/Talk/TalkApi.php
app/src/User/UserController.php
app/templates/User/profile-comments.html.twig
app/templates/User/profile-events.html.twig
app/templates/User/profile-talks.html.twig
app/templates/User/profile.html.twig
web/css/joindin.css

Detail pages for each of the summary boxes on the user profile page. 
Also performance improvements.
Note that this PR builds on #185.

User profile detail pages

---

app/src/Event/EventApi.php

Fix for Bug 489. Removed pagination limit

---

app/src/Event/EventController.php
app/src/Search/SearchController.php
app/src/Talk/TalkApi.php
app/src/Talk/TalkController.php
app/src/User/UserApi.php
app/src/User/UserController.php
app/templates/Event/_common/schedule_cell.html.twig
web/css/joindin.css

Reimplemented as per @lornajane's suggestions from the first attempt.

Link to a speaker's profile within the schedule view (2)

---

README.md
web/index.php

Added a bit of documentation and code help for people using the built-in PHP web server for development.

Dev server help

---

app/src/Application/ApplicationController.php
app/src/Event/EventApi.php
app/src/Event/EventController.php
app/src/Search/SearchController.php
app/src/Talk/TalkController.php
app/src/User/UserController.php
tests/Event/EventApiTest.php

Requires #196 to be merged first as that has the Twig changes.

Add user links to the event's recent comments page

---

app/src/Event/EventController.php
app/src/User/UserController.php
app/templates/Event/details.html.twig
app/templates/Talk/index.html.twig
app/templates/_common/login.html.twig

Display login box when needed for comments (JOINDIN-518)

---

app/src/Event/EventApi.php
app/src/User/UserController.php
app/src/View/Functions.php
app/templates/Event/_common/event_header.html.twig
app/templates/Event/_common/summary.html.twig
app/templates/Event/_common/summary_cfp.html.twig
composer.json

This commit adds a more elegant solution fopr displaying dateranges.
It addresses JOINDIN-553

Adds a more elegant date-range solution

---

app/src/User/EmailInputFormType.php
app/src/User/UserApi.php
app/src/User/UserController.php
app/templates/User/username-reminder.html.twig
app/templates/_common/login.html.twig

People log in with usernames but we don't display them on web1 so it's important that they be recoverable

Add the ability for a user to request a reminder of their username

---

web/js/joindin.js

Remove focus from the I'm attending button after pressing it

---

app/templates/_common/login.html.twig

Minor change, but allows me to just press enter when the browser autofills :)

Set autofocus to the username field on the login form

---

app/templates/Event/details.html.twig

The sidebar goes wrong when comments are closed. See https://m.joind.in/event/php-uk-conference-2014

Place divs in correct place.

---

app/src/Application/ApplicationController.php
app/src/User/UserApi.php
app/src/User/UserController.php
app/src/User/UserEntity.php
app/src/User/UserFormType.php
app/templates/Application/not-allowed.html.twig
app/templates/User/profile-edit.html.twig
app/templates/User/profile.html.twig
web/css/joindin.css

Enable a user to edit their name, email, Twitter username and change their password.
Note that this PR depends on API PRs: [169](https://github.com/joindin/joindin-api/pull/169) & [165](https://github.com/joindin/joindin-api/pull/165) which have been merged.
This will close: [JOINDIN-482](https://joindin.jira.com/browse/JOINDIN-482) and [JOINDIN-554](https://joindin.jira.com/browse/JOINDIN-554)

User profile edit

---

app/templates/Event/call-for-papers.html.twig
app/templates/Event/index.html.twig
web/css/joindin.css

Style tweaks

---

app/templates/User/register.html.twig

Added resend verification email link to register page

JOINDIN-563 #close Link Added.

---

app/src/User/UserController.php

This route was lost when merging the forgot-password work.

Reinstate the user-profile-edit route

---

.gitignore
Gruntfile.js
build.xml
package.json

Adding a grunt task (run by the phing build process) to do a syntax check on our javascript files.

Javascript Lint Check

---

app/templates/Event/comments.html.twig
app/templates/Talk/index.html.twig
web/css/joindin.css

Extended comment boxes to 5 rows.
Closes JOINDIN-588

Comment boxes extended (JOINDIN-588)

---

app/src/Application/ApplicationController.php
app/src/Application/ContactApi.php
app/src/Application/ContactFormType.php
app/templates/Application/about.html.twig
app/templates/Application/contact.html.twig
web/css/joindin.css

Add contact us page;
Closes [JOINDIN-521](https://joindin.jira.com/browse/JOINDIN-521)

Contact us (JOINDIN-521)

---

app/src/Event/EventController.php

Sets Pending events page to display 30 items

---

app/templates/Application/about.html.twig

People often tell us it's hard to know where to start so I tried to rewrite the about page ... but there's still a lot of information here!

Update About page to make it easier to get started

---

app/templates/Event/pending.html.twig

Fixing event description being truncated on pending events list

JOINDIN-594: Full description for pending events

---

app/templates/Talk/_common/talk_header.html.twig

JOINDIN-596 - Slide links now work

---

app/src/Application/ApplicationController.php

Increase the number of events to 10 on homepage.
https://joindin.jira.com/browse/JOINDIN-611

JOININ-611 Increase the number of events to 10

---

web/css/joindin.css

Make the star smaller in the agenda view
https://joindin.jira.com/browse/JOINDIN-606

JOININ-606 Make star smaller in agenda view

---

config/config.php.dist

Easier for development purposes

changing the default to not cache twig templates

---

app/templates/Event/_common/form.html.twig
web/css/joindin.css

Adds link to allow an event admin to cancel changes they've made to an event and return to the event detail page.  Closes #JOINDIN-618 Fixed

Adds cancel link to event edit form

---

app/src/Application/ApplicationController.php
app/templates/Application/about.html.twig
app/templates/Application/apps.html.twig
app/templates/Event/list-hot-events.html.twig

Created a separate twig template for the event list

Listing 5 hot events on the about and apps page.

---

app/src/Application/ApplicationController.php
app/src/Event/EventController.php

Update for PSR-2 compliance

---

web/css/joindin.css

Changed CSS colour to black #000

Change filled star to black

---

app/src/Event/EventEntity.php
app/src/View/Functions.php
app/templates/Event/details.html.twig

Removed custom function and changed the template to use twig date filter

Joindin 535 Add CFP details onto events detail page 

---

app/src/Event/EventController.php
app/templates/Event/index.html.twig

Adds links to open calls for papers to event index sidebar

---

web/css/joindin.css

https://joindin.jira.com/browse/JOINDIN-612

decrease font size for h3 in sidebar - JOINDIN-612

---

app/templates/User/profile-talks.html.twig
web/css/joindin.css

https://joindin.jira.com/browse/JOINDIN-615

New: Added slides link and comments to the user profile talks page

---

app/src/Event/EventController.php
app/templates/Event/_common/summary.html.twig

See https://joindin.jira.com/browse/JOINDIN-610

JOINDIN-610: When event in progress make schedule default

---

app/templates/layout.html.twig

Makes search button submit the form
Previously the search button was non-active, this will make the search button actually submit the search form.

Makes search button submit the form

---

app/src/Event/EventController.php
app/templates/Event/index.html.twig

This provides some feedback to the user that their event is waiting for approval.

Display a banner on event submission

---

app/src/User/UserApi.php
app/src/User/UserController.php

Enable support for web1 user URLs as per JOINDIN-627

JOINDIN-627 Web 1 User URLs

---

app/src/Event/EventApi.php
app/src/Event/EventCommentEntity.php
app/src/Event/EventController.php
app/src/Talk/TalkApi.php
app/src/Talk/TalkCommentEntity.php
app/src/Talk/TalkController.php
app/templates/Event/comments.html.twig
app/templates/_common/comment.html.twig

Allow users to report event and talk comments

---

app/templates/Talk/_common/talk_header.html.twig

Fixes #JOINDIN-602: Removes "Claim talk" link.

---

app/src/Event/EventCommentEntity.php
app/src/Talk/TalkCommentEntity.php
app/templates/_common/comment.html.twig

Stops users from being able to report their own comment

---

web/robots.txt

The test servers have overrides that ban all access

Add a robots.txt file that allows bot access

---

app/templates/Error/404.html.twig

Added a link to the old site in its new location, and another to our contact form.  It's likely this page will be seen a LOT more as we transition so some next steps seemed useful.

Add more info and a contact us link to the 404 template

---

app/templates/layout.html.twig

The banner solicits feedback, so make it easier by providing a link!

Add feedback link in banner

---

app/templates/layout.html.twig
web/css/joindin.css

The login form is below the fold in a lot of cases, so provide a menu item that anchors to it.

Add Login menu item

---

app/templates/_common/login.html.twig

Implements [JOINDIN-675](https://joindin.jira.com/browse/JOINDIN-675)

Jump to login error message on login failure

---

app/src/Event/EventApi.php
app/src/Event/EventController.php
app/templates/Event/_common/reported_comment.html.twig
app/templates/Event/reported-comments.html.twig

Add Accept and Reject buttons to each comment on the reported comments page.
Depends on [API PR 308](https://github.com/joindin/joindin-api/pull/308)

Moderate a comment

---

web/css/joindin.css

I added 15px to the bottom of the row class. I think 15px gives it nice vertical spacing. I tried 5,10, and 15, and I think 15 looks best at all widths.

Added 15px bottom padding to row class for better vertical spacing

---

app/src/Event/EventController.php
app/templates/Event/_common/event_attendees.html.twig

Fixing the issues stopping Gravatars showing on live

[hotfix] Whos attending gravatars

---

app/src/Talk/TalkCommentEntity.php
app/src/Talk/TalkController.php
app/templates/Talk/index.html.twig

Hides rating bar in add comment box if you have already commented.  Sends default rating value if adding an additional comment so the API accepts the comment.

Hides rating bar in add comment box if you have already commented.

---

web/js/bootstrap-timepicker.js

Apply patch to bootstrap-timepicker.js as per open PR on bootstrap-timepicker project. This is a patch that has not been accepted / merged into the bootstrap-timepicker project as yet but is needed to satisfy JOINDIN-697

Patch bootstrap-timepicker.js satisfies JOINDIN-697

---

app/src/User/UserApi.php
app/src/User/UserController.php
app/templates/User/profile-edit.html.twig

Re-built the branch without all the messed up commits :-)

Delete User Frontend and Controllers

---

.editorconfig
CONTRIBUTING.md
app/src/Application/BaseApi.php
app/src/Application/ContactApi.php
app/src/Event/Constraint/ValidEventIconValidator.php
app/src/Event/EventApi.php
app/src/Event/EventController.php
app/src/Event/EventFormType.php
app/src/Event/TrackApi.php
app/src/Search/SearchController.php
app/src/Talk/TalkApi.php
app/src/Talk/TalkFormType.php
app/src/User/UserController.php
app/src/User/UserEntity.php
app/src/View/Functions.php
app/templates/Application/contact.html.twig

This helps prevent and fix some instances of PSR-2 (see: #121 ) whitespace oops when editing files.
See [editorconfig](http://editorconfig.org/) for more info about this config file and the editors that support it.

Define whitespace

---

app/src/User/UserController.php

I searched across the project usages of "not-allowed" page, and just the "user-profile-edit" was missing the "redirect" parameter.

Fixing redirect after not-allowed action JOINDIN-701

---

app/src/Talk/TalkApi.php
app/src/Talk/TalkController.php
app/src/Talk/TalkEntity.php
app/templates/Talk/index.html.twig

Creating web2 frontend for new claim talk endpoint.

Claim talk frontend

---

app/src/Event/EventApi.php
app/src/Event/EventController.php
app/src/Event/EventEntity.php
app/templates/Event/_common/event_nav.html.twig
app/templates/Event/pending-claims.html.twig

The final piece of the puzzle - this allows hosts to approve talk claims from speakers.
Depends on https://github.com/joindin/joindin-web2/pull/368

View pending claims

---

README.md

There's currently no mention on the readme that the project is following PSR2.  Due to a minor confusion in IRC chat (namely on my side) I decided to add a small statement to the readme to indicate that PSR2 is used.

Adds code style statement to readme

---

app/src/Client/ClientApi.php
app/src/Client/ClientController.php
app/src/Client/ClientDeleteFormType.php
app/src/Client/ClientEntity.php
app/src/Client/ClientFormType.php
app/templates/Client/_common/client.html.twig
app/templates/Client/_common/deleteform.html.twig
app/templates/Client/_common/form.html.twig
app/templates/Client/delete-client.html.twig
app/templates/Client/details.html.twig
app/templates/Client/edit-client.html.twig
app/templates/Client/index.html.twig
app/templates/Client/submit.html.twig
composer.json
vendor/composer/ClassLoader.php
vendor/composer/autoload_namespaces.php
vendor/composer/autoload_real.php
web/index.php

This PR adds an interface to list, show, edit and delete 3rd party apps.
As a user I can see my (and only my) apps that I registered for access to the joind.in API. This uses the API-changes from https://github.com/joindin/joindin-api/pull/383
This UI can be viewed via /client - There is currently no link or button available. Should this be merged we'd need to define where the interface should be implemented

Allows display of 3rd party apps

---

app/src/Apikey/ApikeyApi.php
app/src/Apikey/ApikeyController.php
app/src/Apikey/ApikeyDeleteFormType.php
app/src/Apikey/ApikeyEntity.php
app/templates/Apikey/_common/deleteform.html.twig
app/templates/Apikey/delete.html.twig
app/templates/Apikey/index.html.twig
app/templates/Client/delete-client.html.twig
app/templates/User/profile.html.twig
composer.json
vendor/composer/autoload_namespaces.php
web/index.php

This commit adds a way to see and delete API-keys that are registered for the current user.
This adds the functionality provided in the legacy-app via https://legacy.joind.in/user/apikey

Adds User-Interface to handle API-Keys

---

app/src/Event/EventApi.php
app/src/Event/EventController.php
app/src/Talk/TalkApi.php
app/src/Talk/TalkController.php
app/templates/Event/pending-claims.html.twig

Added reject button
Added exception as a use statement

JOINDIN-642

---

app/src/Talk/TalkApi.php
app/src/Talk/TalkController.php
app/src/Talk/TalkEntity.php
app/src/User/UserEntity.php
app/templates/Talk/_common/talk_header.html.twig

Work in progess, feedback appreciated

Add ability to unlink an approved speaker from a talk #JOINDIN-647

---

app/src/Event/EventController.php
app/templates/Event/pending-claims.html.twig

@liam-wiltshire  This is the fix for rejecting a claim.
Also it looks like the looping was in the wrong place. Fixed that

JOINDIN-642 Additional fix

---

app/src/Client/ClientController.php
app/templates/Client/_common/client.html.twig

As we talked about the clients should also go into the users namespace.
So this PR handles that.

Moves Clients to users namespace

---

app/src/User/AuthApi.php
app/src/User/UserController.php
app/templates/_common/login.html.twig

Added in check to see if error message is Not verified and if so display the correct message
Part of #JOINDIN-718

Updates login so displays correct error message

---

app/templates/Talk/_common/talk_header.html.twig
app/templates/Talk/index.html.twig

Signed-off-by: David McKay <david@rawkode.com>

Ensuring ampersands in talk titles are decoded when printed

---

app/src/Application/ApplicationController.php
app/src/Application/CacheService.php
app/src/Client/ClientController.php
app/src/Event/EventController.php
app/src/Search/SearchController.php
app/src/Talk/TalkController.php
app/src/User/UserController.php
tests/Event/EventApiTest.php
web/index.php

Refactored controllers and services to use built in Slim DI container

---

app/templates/Event/schedule-grid.html.twig
app/templates/Event/schedule-list.html.twig

Fixes to some layout breakages in some cases due to dsplaying starred-only talks.

Fixes for starred layout

---

app/src/Talk/TalkApi.php

Fixes #420 
Doesnt add delete button, Dont have time to add that currently but will try and update that!

Fix Talk Links

---

app/templates/Talk/_common/form.html.twig

Resolves https://github.com/joindin/joindin-web2/issues/420

Add delete link to newly created media entries

---

app/src/Talk/TalkApi.php

if the Talk media is blank, Dont try and add it

Skip Blank talk media

---

app/src/User/RegisterFormType.php
app/src/User/UserController.php
app/src/User/UserEntity.php
app/src/User/UserFormType.php
app/templates/User/profile-comments.html.twig
app/templates/User/profile-edit.html.twig
app/templates/User/profile-events.html.twig
app/templates/User/profile-talks.html.twig
app/templates/User/profile.html.twig
app/templates/User/register.html.twig
web/css/joindin.css

This will allow a user to add some more information regarding their occupation, specialization, interests and experience. That additional information can be useful for users interested in a speaker, for event organizers to get a feel for a speaker or for getting some context behind a comment.
This PR depends on changes in the API made in joindin/joindin-api#449

Allow users to add a small biography to their profile

---

app/src/User/AuthApi.php
app/src/User/UserApi.php

Json Decode with Big Ints

---

web/index.php

Its currently a session cookie, this will make it a week long. This will stop logging people out

Update the default session time

---

app/templates/Application/apps.html.twig

Removes the links to the mobile apps and adds text about using existing site on mobile.

Deprecates mobile apps

---

app/templates/Application/about.html.twig

Removed some text about Apps and web2 being on m.joind.in

Updates about page

---

web/index.php

Need to over ride redis and set default timezone

Add Docker Support

---

app/templates/layout.html.twig

Remove next gen banner

---

app/src/Event/EventApi.php
app/src/Event/EventFormType.php
web/js/joindin.js

The API already kicks out invalid data, This is just adjusting the front
end
fixes #672

Validate times are in correct order

---

app/templates/Application/contact.html.twig
app/templates/Event/_common/event_header.html.twig
app/templates/Event/comments.html.twig
app/templates/Event/pending.html.twig
app/templates/Event/reported-comments.html.twig
app/templates/Talk/index.html.twig
app/templates/User/profile-edit.html.twig
app/templates/User/profile.html.twig
app/templates/_common/login.html.twig

Fix escaped HTML

---

app/src/Apikey/ApikeyController.php
app/src/Event/EventApi.php
app/src/Event/EventController.php
app/src/Talk/TalkApi.php
app/src/Talk/TalkFormType.php
app/src/User/UserApi.php
app/src/User/UserController.php

Fixes some minor issues found while doing static analisis

fixes static analisis issues

---

composer.json

This PR brings the licence section in composer.json in line with the LICENCE file of the project

changes the licence in composer.json to BSD-3-Clause matching the LICENCE file

---

config/config.php.dist
web/index.php

Moves default redis server to the config so it can be configured in platform.sh

Fix for platform.sh redis.

---

app/templates/layout.html.twig
composer.lock

Also bumps us to a Twig version that the security checker doesn't complain about

Update sponsor logo to platform.sh

---

app/templates/Event/schedule-grid.html.twig

fixes grid layout for multiple tracks at same time

---

app/templates/Application/about.html.twig

Fix EIN number

---

app/src/Application/ApplicationController.php
app/templates/Application/about.html.twig
app/templates/Application/assets.html.twig
app/templates/Event/list-upcoming-events.html.twig

Fixed Issue #845 
@svpernova09 Could you please check the commits for this pull request and let me know ? 
Also , i wasn't sure which was the homepage under .../templates so i couldn't change that !

Fixed Issue #845

---

CONTRIBUTING.md
README.md
app/templates/Application/about.html.twig
app/templates/Error/app_load_error.html.twig

Replace links to IRC w/ Slack

---

.gitignore
app/src/Apikey/ApikeyController.php
app/templates/Apikey/index.html.twig
app/templates/_common/pagination.html.twig
composer.lock

Added active pagination to API Keys page.
1. **Page location memory** - the last viewed pagination index is stored in the session data so the user is returned to the same location the next time they visit the API Keys page.
2. **Fewer results per page** - the API Keys page now displays 10 records at a time to bring the pagination buttons further up, making them easier to access without the user having to scroll down.
3. **Pagination button visibility** - the pagination buttons will only be displayed when there are more than 10 records for the user in the oauth_access_tokens table.

765 adding pagination info and controls to api keys

---

app/templates/layout.html.twig

Update footer w/ links

---

app/src/Event/EventController.php
app/src/User/UserController.php
web/index.php

Change name of session

---

app/src/Event/EventEntity.php
app/templates/User/profile-comments.html.twig
app/templates/User/profile-edit.html.twig
app/templates/User/profile-events.html.twig
app/templates/User/profile-navigation.html.twig
app/templates/User/profile-talks.html.twig
app/templates/User/profile.html.twig

2 tasks accomplished here
1. Clean up profile navigation by extracting to it's own include template
1. Add method to return pending status for displaying to user an event they host is pending

Extract profile navigation to template, Add pending field to event data

---

manifest.json

Added manifest.json file for PWA display standalone feature for latest Android and IOS OS

Added manifest.json

---

app/src/Middleware/TrailingSlashMiddleware.php
tests/Middleware/TrailingSlashMiddlewareTest.php
web/.htaccess
web/index.php

This PR is based on @mloberg's original work but adds in unit tests for the new middleware. I originally PR'd against his repo, but this brings in their code plus the tests and rebases on top of the latest master code at the time this PR was created.

Redirect trailing slashes so they work

---

app/src/Apikey/ApikeyApi.php
app/src/Application/ApplicationController.php
app/src/Application/BaseApi.php
app/src/Client/ClientApi.php
app/src/Event/EventApi.php
app/src/Event/EventController.php
app/src/Event/EventFormType.php
app/src/Event/EventScheduler.php
app/src/Event/EventSchedulerDay.php
app/src/Event/TrackApi.php
app/src/Form/DataTransformer/DateTransformer.php
app/src/Middleware/TrailingSlashMiddleware.php
app/src/Search/SearchController.php
app/src/Talk/TalkApi.php
app/src/Talk/TalkFormType.php
app/src/User/AuthApi.php
app/src/User/UserApi.php
app/src/User/UserController.php
app/src/View/FiltersExtension.php

Included are a number of fixes from PHPStan at level 5. It does not
solve all problems PHPStan calls out for level 5 but it does get
quite a few. After applying this patch, there are 45 remaining issues
at level 5 and 117 at level 7.

PHPStan fixes for level 5

---

app/src/Event/TrackApi.php
app/src/Event/TrackFormType.php
app/templates/Event/edit-tracks.html.twig

Resolves #870 once joindin/joindin-api#734 is merged to support server side.

Don't require tracks to have a description

---

app/src/Event/EventController.php
app/src/Talk/TalkController.php
app/src/User/UserController.php

#883 phpstan fixes

---

app/templates/Talk/_common/talk_header.html.twig

Add talk end time to talk detail view.

 Add talk end time to talk detail view Fix #872

---

app/templates/Event/_common/event_details.html.twig
app/templates/Event/details.html.twig
app/templates/Event/pending.html.twig

Adds noreferrer and noopener attributes to user defined external links

add noreferrer and noopener to user defined urls

---

app/src/Event/EventApi.php
app/src/Event/EventController.php
app/src/Event/EventEntity.php
app/src/Event/EventHostFormType.php
app/templates/Event/_common/event_nav.html.twig
app/templates/Event/eventhosts.html.twig
web/css/joindin.css

This allows to add multiple hosts to an event via the UI. All of the hosts have the same privileges! There is no specific validation step as adding or removing a host is super easy.
This fixes #588

Provide UI to manage hosts of an event.

---

app/src/User/UserController.php

Was looking at #690 and found this as a quick fix if it works for you all.

Redirect check so redirect to /not-allowed sends the user back to /

---

app/templates/Talk/_common/talk_header.html.twig

I know there is an issue (#896) to make the track optional so I make this change assuming that would get taken care of soon. 
I'm trying to contribute this as part of hacktoberfest but I'm not able to select the label.
This closed #871

Added track names to talk detail view

---

app/src/Talk/TalkController.php
app/src/Talk/TalkFormType.php

This PR makes the "track" selection optional on the talk form.
Closes #896

Make the track selection option on the talk form.
