app/src/Application/ApplicationController.php, app/src/Event/EventApi.php, app/src/Event/EventController.php, app/src/Search/SearchController.php, app/src/Talk/TalkApi.php, app/src/Talk/TalkController.php, app/src/Talk/TalkDb.php, app/src/User/UserApi.php, app/src/User/UserController.php, app/src/User/UserDb.php, tests/Event/EventApiTest.php
Main things:
* Renamed EventApi's getCollection to getEvents and queryEvents to getCollection to be consistent with TalkApi
* In all controllers we now have a set of get methods which handle creation of CacheService, Db and Api objects as required. This ensures that we don't accidentally create two CacheService instances by accident and makes it clearer what's going on in the controller methods as there's a little less boilerplate.
* EventApi's getByFriendlyUrl and getByStub now use getEvent so that they also save to eventDb on successful retrieve.
* Tidied variable names so that a $talk or $event is always an Entity.
* Fixed trying to access an array element that may not exist in TalkDb.
* Ensure that we save the meta data to the db object consistently in the Api classes whenever we …
=> A collection of minor tidy-ups

app/src/Event/EventApi.php, app/src/Event/EventCommentEntity.php, app/src/Event/EventController.php, app/src/Event/EventEntity.php, app/templates/Event/details.html.twig, tests/Event/EventApiTest.php
Allow a user to optionally rate an event when commenting. 
Display the average rating for an event if it's not zero.
This should be merged after API PRS: [171](https://github.com/joindin/joindin-api/pull/171) & [172](https://github.com/joindin/joindin-api/pull/172)
JOINDIN-544 #close Fixed.
=> Event ratings

app/templates/Event/details.html.twig
Ensures that map will only display if co-ordinates have been set and are not 0
Fixes #JOINDIN-560
=> Only show map if co-ordinates exist and are not 0

app/src/User/AuthApi.php, app/src/User/UserController.php, app/templates/_common/login.html.twig
This relies on the related API pull request: https://github.com/joindin/joindin-api/pull/190 and will also fix #463
Adds a "log in with twitter" link to the login page which should prompt you to grant access for joind.in to read only on your twitter account (prompting you to log in with twitter as appropriate).  If the twitter nick you sign in as is listed on a joind.in account, we'll sign you in as that account.
Does not cover:
- registration
- the fact that twitter accounts aren't unique
=> Sign in with twitter

app/src/Talk/TalkApi.php
JOINDIN-605 #close Fixed.
TalkEntity::getEndDateTime() can return null when the duration is not
set. This means that format method of the date cannot be used. Since the
variable $endTime is not being used anyway, it should be removed.
Before merging this, we should consider whether
TalkEntity::getEndDateTime() is still needed? I've found no other uses
of this and am happy to amend this PR to include the removal of this 
method should that be preferable.
=> Remove unused talk end time variable

app/templates/Event/comments.html.twig, app/templates/Talk/index.html.twig
As a visitor enters a comment, once the comment exceeds default of 7
lines it will start to expand the textarea vertically.
Closes #JOINDIN-589
=> Enables automatic textarea expansion on comment fields

app/src/Event/EventApi.php
After creating the event entity object for each event in the collection we need to find the username of each host so that we can link to them.
This is currently used in the pending events list page, but due to the caching in redis, is not an especially expensive operation to do anyway.
To test this, look at the Pending events list page and note that before this patch, the host's name is unlinked, and then when applied, the name is linked to their profile.
=> Retrieve host username in event collection

app/templates/Event/_common/summary.html.twig, app/templates/Talk/_common/summary.html.twig, app/templates/_common/eventtitle.html.twig
Link to comments has to be a slash instead of a hash.
Fixes: https://joindin.jira.com/browse/JOINDIN-614
=> JOINDIN-614 - Fix link to event comments

app/templates/Event/schedule-grid.html.twig
Alter template to make Social Events span across all tracks in the giid view in the same way Keynotes do.
Also alter talk.type comparisons to use lower case strings in the template as the api code seems to show "Social event" as a valid talk type yet the api is producing "Social Event" as an talk type for events
http://api.joind.in/v2.1/talks/15553
=> Joindin 624

README.md, app/src/Application/BaseApi.php, config/config.php.dist
When debugging, I find it helpful to push my API calls through a proxy such as Charles or mitmproxy, but it needs a minor modification to the code that makes the API calls to add the proxy setting to the stream context.  This patch makes this configurable and doesn't proxy if the setting is missing or empty.
=> Config to make all API calls go through a proxy

web/css/joindin.css
- Fixed issue with the 'session key'
container-fluid overflowing when breakpoint > 1200px
=> Fix issue with the sessions key overflowing the container

app/templates/Event/_common/attending_string.html.twig, app/templates/Event/_common/event_header.html.twig, app/templates/Event/_common/summary.html.twig, app/templates/Event/details.html.twig
The main focus of this PR is JOINDIN-616 but this lead to other issues being discovered.
The jquery associated with the "attending event" button (on the event page) did not function correctly due to missing elements.
This was fixed by using the existing template for the attending string.
The attending string template was altered to increase re-usability
=> Joindin 616 - Move "attending event" button and associated issues

package.json
When running `phing jsvalidate`, we get a couple of npm warnings related to being a good public repository citizen. As this is a private package, we set `private` to `true` to remove these unnecessary warnings.
=> Remove npm warnings

app/templates/Event/_common/form.html.twig, web/js/joindin-map.js
With m.joind.in running over HTTPS, the HTTP-only OpenStreetMap search wasn't working on the event submission page, and the loading of the map tiles over HTTP was showing as a warning in Chrome.
=> Use OpenStreetMap over HTTPS

app/templates/Event/details.html.twig
Only shows event short url if event_stub is set
Per Akrabat's comment on JIRA setting to only show the URL if event_stub is set.  Open for other suggestions.
Closes #JOINDIN-593 fixed
=> Only shows event short url if event_stub is set

app/src/Talk/TalkController.php
From Jira:
> web1's long form talk urls of the format {{talk/view/15425}} need to work on web2
> This should be implemented with a new route that reuses the {{TalkController}}'s {{quickById}} action
=> New: Added compatibility route for /talk/view/<id> URL from web1

.gitignore, web/css/joindin.css
I changed the margin-left from 120px to 150px in the joindin.css file.
=> Fixed Event Pending Description so the description body isn't wrapping around the buttons

app/templates/Event/schedule-grid.html.twig, web/css/joindin.css
Update the session key in grid view so that it always displays as a single line rather than resizing to a block of 5 at smaller window sizes. This makes the key far less intrusive.
=> Display session key as a single line in all sizes

app/src/Event/EventApi.php
If the event fails to submit, the text is more friendly if we decode the JSON and tidy the meta text a little.
=> Better error message display when submitting an event fails

app/templates/Event/pending.html.twig
The meta data (where, when, hosts, etc) needs to be above the
description now that the description may be many paragraphs long. This
makes it easier to assess whether to approve the even without having
to scroll.
=> Move meta data to top on event pending page

app/templates/Event/details.html.twig
By sharing links on social network sometimes the system picks up the wrong image. This tags forces the image that will appear in the post.
But this is still not good enough. The image size is very low and I think we have to add on other pages as well. I don't understand why we don't have (removed) the speaker's image in the talk details page.
We can add another metas too. ex:
```html
<meta name="twitter:site" content="@user">
<meta name="twitter:creator" content="@user">
<meta name="twitter:url" content="http://url.com">
<meta property="og:url" content="http://url.com">
<meta property="og:title" content="title">
<meta property="og:description" content="desc">
<meta name="description" content="desc">
```
=> Adding social meta for event image

app/templates/_common/comment.html.twig
Users must be logged in to report a comment, so don't show the links to
users who aren't logged in.
=> Don't show the report comment link unless logged in

app/src/User/UserController.php
With this change, `http://web2.dev.joind.in/user/[user]/hosted` should now show all events the user has ever hosted. Currently, it only shows 5 (e.g. https://m.joind.in/user/asgrim/hosted):
=> Show all events on user-hosted page

app/src/Event/EventFormType.php
It turns out that some venue names are only two characters, so having validation that requires three characters is not helpful...
=> Allow any length of venue name

app/src/Event/EventController.php
We have support for /event/view/1234 but web1 also had a variety of
other things after the ID, including talk_comments.  This redirects
talk_comments appropriately and just sends the user to the event page
rather than the 404 page for all other trailing content
=> Handle web1 URLs /event/view/X/stuff

app/src/Talk/TalkController.php
It's possible with a direct link that the event isn't in the Redis cache, so grab from the API if this happens.
=> Use API if we can't find event in DB in quickById()

app/src/User/UserController.php
URLs of the form `/user/view/24206` may have additional segments that were valid on web1. We want to match and ignore as we don't use them, but do want them to redirect to the user's profile page.
=> Add catchall on old user URL

app/templates/User/profile-talks.html.twig
The event part of the URL was missing and so the links didn't work
=> On user talks page, link comment count to talk

web/.htaccess
We used to have images such as /inc/img/rating-4.gif which are used by our js widgets and also by other people using joindin data on their blogs.  This rewrite rule returns our new rating images at those existing URLs.
=> Serve new rating images at old rating image URLs

app/src/Talk/TalkApi.php
If the talk doesn't exist in the API, return false rather than cause an exception error.
Fixes https://joind.in/talk/view/2721 so that it returns a 404 rather than a 500.
=> Return false when talk doesn't exist

web/.htaccess
We don't support /feed URLs from the legacy site any more, so inform clients that they are gone.
=> Send a 410 for feed URLs

app/src/Event/EventController.php, app/templates/Event/schedule-grid.html.twig, app/templates/Event/schedule-list.html.twig
As reported by Eli White, when first viewing an event, display the  schedule rather than the details page. Also, update the schedule page with the first paragraph of the description for context and a message if there are no talks for this event.
Note that the work in #320 will need updating when this is merged.
=> Display the event's schedule by default

app/src/View/Functions.php, app/templates/Event/_common/event_header.html.twig, web/css/joindin.css
Expose the current route to Twig and then use this to set the active class for the submenu navigation on the event page. Override the default active style to simply bold the current submenu item.
<s>Note that this will need changing if #321 is merged.</s>
=> Highlight current submenu item on event page

app/src/View/Functions.php, app/templates/Event/_common/layout_event_details.html.twig, app/templates/Event/comments.html.twig, app/templates/Event/details.html.twig, app/templates/Event/schedule-grid.html.twig, app/templates/Event/schedule-list.html.twig, app/templates/Event/talk-comments.html.twig
If someone shares an event from joind.in on social media, provide the relevant open graph protocol data along with the additional Twitter meta data. I've done this for all pages as going forwards is likely that one of the schedule pages will be the shared page, not just the detail page. The comments pages are unlikely to be shared, but it seemed sensible to be consistent.
=> Implement open graph meta data on all event pages

app/src/Application/ApplicationController.php
This commit changes the number of CfPs displayed on the main page from 10 to 4. That way the site doesn't look that cluttered anymore.
=> Changes max number of displayed CfPs to 4

app/templates/Event/_common/summary_cfp.html.twig
Currently in the list of upcomming CfPs there is no information given to when the CfP starts and/or ends. This is due to wrongly named methods for CfP-Date-retrieval. I've fixed these function names and now the CfP-Info is displayed again.
=> Fixes broken display of CfP-Dates

app/templates/Talk/index.html.twig
As we're getting so many questions on this, add the claim talk button to the talk page (if you're logged in) and open a popup with a link to the legacy site.
Images: 
* Claim talk button: https://i.19ft.com/a7a5bcd9.png
* Popup: https://i.19ft.com/35bc0714.png
=> Add claim talk button with link to legacy site

app/src/Event/EventApi.php, app/src/Event/EventCommentReportEntity.php, app/src/Event/EventController.php, app/src/Event/EventEntity.php, app/src/Talk/TalkCommentReportEntity.php, app/templates/Event/_common/event_header.html.twig, app/templates/Event/reported-comments.html.twig
This just adds a "reported comments" link for event and site admins to
the event navigation, and shows the comments (using the existing comment
template) with information about who reported them.
=> Display reported comments

app/src/Event/EventController.php
Currently on the main entry page only 4 CfPs are shown. Until now the /event-page showed 10 CfPs as that one slipped my eyes when I altered showing only 4 CfPs. 
So this is the fix to that.
=> Fixes number of CfPs on Event-subpage

app/src/Event/EventController.php, app/templates/Event/_common/event_pagination.html.twig, app/templates/Event/index.html.twig
Use the API's "all" filter for the events list so that we can go backwards as well as forwards
If the page query parameter is not set, then do not pass a start number to the API's so that the event's "all" filter will return the first page of events where at least one event is in the future. That is, we get a list of events positioned at "now".
In this case, we have to work out the current page number ourselves, which we do by looking at the this_page meta field which contains the correct start parameter.
Depends on https://github.com/joindin/joindin-api/pull/295
Fixes [JOINDIN-499](https://joindin.jira.com/browse/JOINDIN-499)
=> Enable listing of previous events

app/src/User/UserController.php, app/templates/_common/login.html.twig
Rather than always jumping to the login form after authenticating, it is better to only jump to it on login failure.
This PR will remove the `#loginheader` fragment that you see in the URL after logging in.
=> Better redirect on login failure

app/src/Event/EventFormType.php
The date fields on the event form need the `form-control` class in order to match the style of all the other elements on the form.
=> Fix style of date fields on event form

app/templates/Event/_common/form.html.twig, app/templates/Event/edit.html.twig
As in title.
I've added a guideline in the sidebar as suggested in the issue, and also a short help message below the upload field in the form, so it's immediately visible, even on mobile.
=> Adding icon submission guidelines (solves JOINDIN-695)

app/src/Application/BaseController.php, app/src/Event/EventController.php, app/src/Event/EventEntity.php, app/src/Event/TrackApi.php, app/src/Language/LanguageApi.php, app/src/Talk/SpeakerFormType.php, app/src/Talk/TalkApi.php, app/src/Talk/TalkEntity.php, app/src/Talk/TalkFormType.php, app/src/Talk/TalkTypeApi.php, app/templates/Event/_common/event_header.html.twig, app/templates/Event/_common/event_nav.html.twig, app/templates/Event/add-talk.html.twig, app/templates/Event/edit.html.twig, app/templates/Event/index.html.twig, app/templates/Talk/_common/form.html.twig, app/templates/layout.html.twig, composer.json, vendor/composer/autoload_namespaces.php, vendor/composer/autoload_static.php, web/css/bootstrap-timepicker.css, web/css/joindin.css, web/js/bootstrap-timepicker.js
Add the ability to add a talk to an event. 
This PR also implements the yellow admin bar for the event section as we now have three items for it and will have more, so this seemed a good time to to do it.
The ability to add speakers when adding the talk is also implemented. This works the same way as web1 and depends on [API PR #320](https://github.com/joindin/joindin-api/pull/320).
In order for the talk to be added to the selected track, [API PR #328](https://github.com/joindin/joindin-api/pull/328) is required.
=> Add talk to an event

app/src/Event/EventController.php, app/src/Event/TrackApi.php, app/src/Event/TrackCollectionFormType.php, app/src/Event/TrackFormType.php, app/templates/Event/_common/event_nav.html.twig, app/templates/Event/edit-tracks.html.twig, web/css/joindin.css
Ability to add, edit and delete tracks from an event.
This is implemented as a page containing a form with a collection of track form-types in it, so we can implement the functionality as a single page.
Requires PR [#338 (Add talk to an event)](https://github.com/joindin/joindin-web2/pull/338) as that one has the new admin nav bar in it.
=> Track administration

app/src/Talk/TalkController.php
If the user is not logged in, don't check if the talk can be edited.
Fixes 500 error that's currently one live!
=> Ensure user is logged in for canEditTalk flag

app/src/Talk/TalkController.php, app/templates/Talk/index.html.twig
Solves JOINDIN-684 by ensuring that the comment is re-populated into the form if no rating was provided, and vice-versa (maintains the rating if no comment was provided).
Also ensures that the correct anchor is returned in all error instances (Spam, Duplicated, etc.)
=> Keep comment if no rating validation fails - solves JOINDIN-684

app/src/Event/EventApi.php, app/src/Event/EventController.php, app/src/Event/EventEntity.php, app/templates/Event/_common/event_attendees.html.twig, app/templates/Event/details.html.twig, web/css/joindin.css
Creates a basic sidebar block to show event attendees - shows 6 to start, with the rest loaded via AJAX on request (otherwise there could potentially be a pretty substantial performance hit for big events!)
The styling is fairly basic - it works and looks 'fine' I guess, but no doubt someone could pick it up and make it look better once it's in.
=> Add who's attending block to event details page - satisfies JOINDIN-621

CONTRIBUTING.md, composer.json, composer.lock, vendor/composer/ClassLoader.php
This started out as a search to figure out which version of PHP I should write against as a new joind.in dev. I first looked in the `CONTRIBUTING.md` file and didn't find anything. I then looked at the `composer.json` file and didn't see anything. However,`"preferred-install": "dist"` being a top-level setting in `composer.json` appeared to be incorrect, so I looked into where it needed to be: it needs to be in a config.
This PR attempts to fix both issues.
As a bonus, I guess, Composer 1.2.1 (latest version at this time) wanted to make some changes to the logic in Classloader. Those changes are part of this PR as well.
=> Composer improvements

app/templates/Event/talk-comments.html.twig, app/templates/_common/comment.html.twig
Alter twig templates to enable correct 'report comment' url to be used for the event/talk-comments view.
=> JOINDIN-698 #close

app/src/Event/EventScheduler.php
This fixes a logic error where the parentheses in an if-statement were misplaced. 
This replaces a `count` being greater than zero with a check for not- `empty`, since that's really what the intent is here.
=> Fix error in checking for empty array

app/src/Event/Constraint/ValidEventIconValidator.php, app/src/Event/EventApi.php, app/src/Event/EventScheduler.php, app/src/Talk/TalkApi.php, app/src/Talk/TalkController.php, app/src/User/UserApi.php, app/src/User/UserController.php
This is so existing violations don't trip up a future PR.
These were fixed via `phpcbf --standard=PSR2 app/`
=> Fix existing PSR2 violations

app/src/Application/BaseApi.php, app/src/Application/BaseCommentEntity.php, app/src/Application/BaseCommentReportingEntity.php, app/src/Application/BaseController.php, app/src/Application/BaseDb.php, app/src/Application/BaseEntity.php, app/src/Application/Config.php, app/src/Application/ContactApi.php, app/src/Event/EventCommentEntity.php, app/src/Event/EventCommentReportEntity.php, app/src/Event/EventController.php, app/src/Event/EventDb.php, app/src/Event/EventEntity.php, app/src/Event/TrackApi.php, app/src/Language/LanguageApi.php, app/src/Search/SearchController.php, app/src/Talk/TalkCommentEntity.php, app/src/Talk/TalkCommentReportEntity.php, app/src/Talk/TalkDb.php, app/src/Talk/TalkEntity.php, app/src/Talk/TalkTypeApi.php, app/src/User/UserDb.php, app/src/User/UserEntity.php
This is a code cleanup PR.
This formally declares two classes that were being used as abstract classes as abstract. This also extracts out some more abstract classes to make it easier to identify differences between like-classes.
I found a logic bug the EventScheduler while I was running through this, so I've also included its fix in this PR. If you'd prefer that fix be in a separate PR, let me know and I will split it out. (edit: split out to #375 )
=> Use abstract classes

app/src/User/UserApi.php
This class property existed without being explicitly declared. Was it public? private? protected? This commit resolves that question.
=> Add missing property

app/src/User/UserController.php
While researching another issue I noticed my PHPStorm complaining about unused variables. As it turns out, in quite a few places in the `UserController` the `$result` variable is being initialized with value `false`, but it is never used in the scope where it is defined. It is used later, but set to another value before usage. The initializing of `$result` to `false` therefore seems useless. In the spirit of leaving the code better than you found it, I decided to clean it up :)
=> Removing the setting of $result in places where it isn't used

app/src/Client/ClientController.php, app/templates/Client/_common/client.html.twig, app/templates/Client/details.html.twig, app/templates/Client/edit-client.html.twig, app/templates/Client/index.html.twig, app/templates/Client/submit.html.twig, app/templates/User/profile.html.twig
This alters the URI for the clients-endpoints from ```/client``` to ```/user/[username]/client```.
That also adds a further test to make sure the provided username matches the currently logged in user. Otherwise a "not-allowed" message will be provided.
This updates all the links and also adds a link to the clients to the UI of the user-profile-page
=> Alters URI for clients

app/src/View/Functions.php, app/templates/Event/details.html.twig, app/templates/Talk/_common/talk_header.html.twig
This PR adds a link to an QR-Code to the event- and the talk-details. That way organizers and speakers can easily add a QR-Code to their slides for easier reference of the event or talk. That makes it
easier for attendees to find the talk or event and rate it.
=> Adds QR-Code links to event- and talk-details

app/templates/Application/index.html.twig
I was talking with @yourmark of the WordPress Meetup Enschede. He is not a very regular user of joind.in and he mentioned that he missed a CTA to add an event on the homepage. I decided it was a good idea to get less experienced used on board and create a PR. I hope you like this ;)
=> Added the CTA to submit an event to the homepage

app/templates/layout.html.twig
Fix capitalization on login form heading.
Resolves JOINDIN-738
=> Add anchor tag for login form so the link works.

app/src/Application/BaseApi.php, app/src/User/UserController.php
Noticed today that I couldn't access the pending events page as an admin.
Having done some digging, it was to do with the move to using the Slim container (which is sort-of a registry).
When a user logs in, previously we were creating a new userApi object, which would thus inherit their new token - but this wasn't happening fetching the object from the container, and so the 'admin' property (which is only sent when requested with an admin token), wasn't coming through, and thus wasn't being added to the session.
Have added a method to the baseApi class to allow the access token to be re-set after the object as been created, and updated the handleLogin method to use this.
=> Enable the ability to update the access token

app/templates/Event/index.html.twig
php.ug displays the upcoming events in a map-form so this commit adds a link to that map so that users can have a look at what events are near them…
This currently only shows events with a PHP-Tag. But's that an issue with php.ug that I will most likely remove within the next days…
This handles an idea that Juliette Reinders mentioned at PHP Southcoast. There's no ticket to it…
=> Adds a link to the event-map

app/templates/_common/comment.html.twig
You can easily make a mistake and report the wrong comment and that cannot be undone. This PR adds a basic confirmation when reporting a comment.
=> Issue #428 - Ask or confirmation when reporting a comment

app/templates/Event/schedule-grid.html.twig
Fix issue with disappearing talks in schedule view that share the same name. Reported on Ji raas JOINDIN-750
=> JOINDIN-750 #close

README.md
Seeing as we're no longer using jira, this updates the link in the readme
=> Updates issues list to github

app/templates/Event/schedule-list.html.twig, web/css/joindin.css, web/js/joindin.js
Added a new button group for all lists (it does not apply to the grid as I thought it feels too crowdy). I choose the button group because I think is more expressive and integrates better with that "toolbar" of button groups. 
An alternative would be I think just a checkbox that would word something like "Include talks descriptions". 
What do you think?
=> Feature request: Include talk descriptions on talk list page #440

app/templates/Event/details.html.twig, app/templates/Talk/_common/talk_header.html.twig
I notice whist browsing the site that the QR-Code pages provide no way to intuitively go back to the site. For this reason I inadvertently closed the tab that I was using to browse the site instead of pressing back.
I feel this PR is an improvement to the current system as it adds the functionality to open the QR-Code's in new tabs.
=> Add target _blank to href tags for QR code links

app/src/User/UserApi.php
Web2 has a cache system using redis that seems to be used for no real reason in this case. 
What is that advantage of looking up a cached API URI for a user and then using that uri to fetch the user from the API vs asking the API for a user matching a specific username? 
The only assumption (i have checked as far as I can) I am making here is that usernames are unique and that asking the API for a user by username will only return one result. This should not be an issue though as in the current code on a cache miss the user is fetched from the API by username, the first result used, and then the resulting user URI is cached to a key of the users username so in effect if multiple users were an issue then it would still be an issue.
I really see no need for this complexity in the code.
=> Remove Pointless Cache Complexity

app/src/View/FunctionsExtension.php, tests/View/Fixtures/functions/qrcode.test
This works because all of our links that are QR coded don't have query string parameters.
This way we can look at web server logs or similar to see how often people actually use QR codes.
=> Allow us to tell QR coded links from normal ones

.travis.yml, composer.json, composer.lock
Now that we're using PHP 7.3.2 on the vm, make that the target version for composer installs.
Takes care of #780
=> Upgrade to PHP 7.3

app/src/Application/ContactFormType.php, app/templates/Application/contact.html.twig, web/css/joindin.css
This adds a Form-Field that has to be empty. A so called HoneyPot. A
trap for bots that usually fill out every form field that seems
relevant. As the introduced field needs to be empty every
form-submission that contains that field will automatically be filtered
out as the form wasn't valid.
=> Add honeypot for contact form

app/src/View/FunctionsExtension.php, app/templates/Error/404.html.twig
This fixes an issue that @exussum12 discovered.
The links to the Grid and the List-view where both broken due to a trailing slash. As we do not use trailing slashes anywhere I removed possibly trailing slashes via a `trim`-call.
Additionally the Error-Page still showed a link to the legacy-site that by now is not available anymore. So I removed it.
=> Fix legacy links

app/src/View/FunctionsExtension.php
We don't want to suddenly turn all our links into relative links when
they were meant to be absolute.
=> Don't trim leading slashes on links

app/templates/layout.html.twig
The Platform.sh logo was a bit on the huge size in the footer-line. This commit fixes that by removing the fixed width and height that did not fit and replacing it with (currently hard-coded) style-information to make it more along the line of what the original CI of platform wanted it to look like.
=> Optimize Platform.sh-logo in footer

web/index.php
Looks like we were swallowing exceptions before?!?
This won't work in development mode, from what I can tell, because dev mode overrides how errors are displayed/handled. But we only really need it for live mode anyway since the idea is that if you're getting errors in dev mode you're somewhere you can look at the stack trace that pops up.
=> Log exceptions via error_log()

app/src/Talk/TalkMediaFormType.php
The issue was that if you have a media link and click ad media link
the form had a different order or type and uri.
=> Align media form with displayed media link info

app/src/Form/Constraint/UrlResolverConstraintValidator.php, app/src/Form/Listener/GetResolvedUrlListener.php, tests/Form/Constraint/UrlResolverConstraintValidatorTest.php, tests/Form/Listener/GetResolvedUrlListenerTest.php
This allows URLs that will be validated to also have a value of NULL instead of only allowing an empty string. Due to the way the values are passed into the validation a non-existent value will become a NULL-value and therefore failed before this fix.
Fixes #827
=> Allow null-values for URL validation

app/src/Event/EventController.php, app/templates/Event/import-csv.html.twig, web/files/EventScheduleCSVImportTemplate.csv
* Fix CSV example which was missing `duration` field
* Add support for multiple speakers via `|` delimeter
* Add note in UI about tracks needing to exist before import
=> Tweaks for Event CSV importing

app/templates/_common/comment.html.twig
Fix for #806
The comment in #806 is not really anonymous, at least not in any way I can see. The user that's on there has no username. So I'm not sure if that's something to do with account deletion, or whatever... But it has an email address. This fix should put the anonymous gravatar in place if the user who made a comment doesn't have a username. 
I haven't been able to find an example of any logged-in, but checked as anonymous that the site used to allow. If anyone has an example of one of those, it'd be pretty helpful.
=> Show anonymous gravatar for users with no username

app/templates/Event/schedule-grid.html.twig
Now the grid is using rowspan attribute to "properly visualize double-length talks in grid view". Not only double-length, actually, but any N-length talks :-)
=>  Use rowspan to properly visualize double-length talks in grid view Fix  #879

app/src/Apikey/ApikeyDeleteFormType.php, app/src/Client/ClientDeleteFormType.php, app/src/Client/ClientFormType.php, app/src/Talk/TalkDeleteFormType.php, app/templates/_common/comment.html.twig, web/index.php
Working to debug why "Report comment" seems to be broken.
This PR is the next step. An attempt to set a HREF to a button.
Not able to reproduce locally but not in production.
Works locally:
But not in production:
Slack convo Debugging w/ @iansltx so far:
```
Joe: I'm testing if https://www.google.com/search?client=firefox-b-1-d&q=window.__cfRLUnblockHandlers is causing our "Report a Comment" to throw "method not found". Reporting comments is fine for me in local dev. But not in prod. Inspecting the HTML shows that __cfRL being injected into our buttons.
Ian: Got it. I can turn off Rocket Loader...and done. lmk if that fixes it
Joe: Nope, no luck. I guess we can turn it back on. I confirmed I didn't see that code in the HTML as I did before, but no change. Thanks for the help. 
```
=> Set the report link type to button

app/src/User/AuthApi.php, app/src/User/UserController.php, app/src/View/FunctionsExtension.php, app/templates/_common/login.html.twig
This PR contains removals for Twitter / X- and Facbook-login for creating an account. Both functions aren't working properly.
Closes #922 
Sidenote: This is my first PR ever, so if you have feedback to optimize it, please let me know.
=> Remove Facebook- and Twittter-login
